/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class DidIdentity {
  reload(): Promise<void>
  snapshot(): Promise<JsIdentitySnapshot>
  pendingRevision(): Promise<JsPendingRevisionSummary | null>
  sign(kid: string, message: Buffer): Promise<Buffer>
  verify(kid: string, message: Buffer, signature: Buffer): Promise<boolean>
  ecdh(kid: string, peerPublic: Buffer): Promise<Buffer>
  publicKeyBytes(kid: string): Promise<Buffer>
  legacyDidWbaHeader(kid: string, serviceDomain: string, version: string): Promise<string>
  httpSignatureHeaders(kid: string, requestUrl: string, requestMethod: string, headers?: Array<JsHeader> | undefined | null, body?: Buffer | undefined | null, options?: JsHttpSignatureOptions | undefined | null): Promise<Array<JsHeader>>
  prepareUpdate(spec: JsDocumentUpdateSpec): Promise<JsPreparedUpdate>
  beginPublication(revisionId: string): Promise<void>
  markPublicationUncertain(revisionId: string): Promise<void>
  markPublished(revisionId: string): Promise<void>
  commitUpdate(revisionId: string): Promise<void>
  abortUpdate(revisionId: string): Promise<void>
  reconcileUpdate(revisionId: string, observedRemoteDocument: any): Promise<string>
  endRetirement(kid: string): Promise<void>
  deleteRevokedKey(kid: string): Promise<void>
}
export type JsDidIdentity = DidIdentity

export declare class DidStore {
  static initializeInjected(root: string, keyId: string, rootKey: Buffer): Promise<DidStore>
  static openInjected(root: string, keyId: string, rootKey: Buffer): Promise<DidStore>
  static initializeEnv(root: string, keyId: string, envVar: string): Promise<DidStore>
  static openEnv(root: string, keyId: string, envVar: string): Promise<DidStore>
  static initializeLocalFile(root: string): Promise<DidStore>
  static openLocalFile(root: string): Promise<DidStore>
  static initializeKeyring(root: string, service: string, account: string, fallbackToLocalFile: boolean): Promise<DidStore>
  static openKeyring(root: string, service: string, account: string): Promise<DidStore>
  generation(): Promise<number>
  manifest(): Promise<JsStoreManifest>
  reload(): Promise<void>
  listIdentities(): Promise<Array<JsIdentitySummary>>
  createIdentity(spec: JsDidCreateSpec): Promise<JsDidIdentity>
  openIdentity(did: string): Promise<JsDidIdentity>
}
export type JsDidStore = DidStore

export interface JsCapabilities {
  didWba: boolean
}

export interface JsDeviceAddSpec {
  deviceId: string
  signingKey: JsDevicePublicKeySpec
  e2eeKey: JsDevicePublicKeySpec
  profiles: Array<string>
}

export interface JsDeviceManifestEntrySpec {
  deviceId: string
  signingKeyId: string
  e2eeKeyId: string
  profiles: Array<string>
}

export interface JsDeviceManifestSpec {
  devices: Array<JsDeviceManifestEntrySpec>
}

export interface JsDeviceMutationSpec {
  operation: string
  device?: JsDeviceAddSpec
  deviceId?: string
}

export interface JsDevicePublicKeySpec {
  kid: string
  publicKeyMultibase: string
}

export interface JsDidCreateSpec {
  profile: string
  domain: string
  port?: number
  pathSegments: Array<string>
  capabilities: JsCapabilities
  managedKeys: Array<JsManagedKeySpec>
  externalKeys: Array<JsExternalPublicKeySpec>
  services: Array<JsServiceSpec>
  agentDescriptionUrl?: string
  extensions: Array<JsDidExtensionSpec>
}

export interface JsDidExtensionSpec {
  extensionType: string
  deviceManifest?: JsDeviceManifestSpec
}

export interface JsDocumentCheckpoint {
  documentVersion: number
  registryVersion: number
  documentDigest: string
}

export interface JsDocumentUpdateSpec {
  requestSigningRotation?: JsRequestSigningRotation
  deviceMutations?: Array<JsDeviceMutationSpec>
  services?: Array<JsServiceSpec>
}

export interface JsExternalPublicKeyMaterial {
  format: string
  value?: string
  publicKeyJwk?: any
}

export interface JsExternalPublicKeySpec {
  kid: string
  role: string
  material: JsExternalPublicKeyMaterial
}

export interface JsHeader {
  name: string
  value: string
}

export interface JsHttpSignatureOptions {
  nonce?: string
  created?: number
  expires?: number
  coveredComponents?: Array<string>
}

export interface JsIdentitySnapshot {
  identityId: string
  did: string
  state: string
  revision: number
  rootCapability: string
  rootKeyFingerprint: string
  checkpoint?: JsDocumentCheckpoint
  document: any
  capabilities: JsCapabilities
  keys: Array<JsKeyMetadata>
}

export interface JsIdentitySummary {
  identityId: string
  did: string
  state: string
  rootCapability: string
  createdAt: string
}

export interface JsKeyMetadata {
  kid: string
  role: string
  origin: string
  state: string
  materialErased: boolean
  version: number
  publicKeyMultibase: string
  createdAt: string
}

export interface JsManagedKeySpec {
  fragment: string
  role: string
}

export interface JsPendingRevisionSummary {
  revisionId: string
  parentRevision: number
  candidateDigest: string
  candidateKids: Array<string>
  state: string
  generation: number
  createdAt: string
}

export interface JsPreparedUpdate {
  revisionId: string
  candidateDocument: any
  candidateDigest: string
}

export interface JsRequestSigningRotation {
  oldKid: string
  newFragment: string
}

export interface JsRootKeyProviderBinding {
  kind: string
  keyId: string
  account?: string
}

export interface JsServiceSpec {
  id: string
  serviceType: string
  serviceEndpoint: string
  profiles: Array<string>
  securityProfiles: Array<string>
}

export interface JsStoreManifest {
  schemaVersion: number
  storeId: string
  generation: number
  provider: JsRootKeyProviderBinding
  rootKeyFingerprint: string
  createdAt: string
  rekeyGeneration: number
}
