/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class DocumentChangeSession {
  candidate(): Promise<any>
  beginPublication(): Promise<any>
  complete(attempt: any, result: any): Promise<any>
  reconcile(observation: any): Promise<any>
}
export type JsDocumentChangeSession = DocumentChangeSession

export declare class IdentityManager {
  static initialize(config: JsIdentityManagerConfig): Promise<IdentityManager>
  static open(config: JsIdentityManagerConfig): Promise<IdentityManager>
  info(): Promise<any>
  list(): Promise<any>
  create(request: any): Promise<JsManagedIdentity>
  get(identity: JsIdentityRef): Promise<JsManagedIdentity>
  delete(identity: JsIdentityRef): Promise<void>
  recover(): Promise<any>
}
export type JsIdentityManager = IdentityManager

export declare class IdentityProvider {
  static initialize(config: JsIdentityManagerConfig): Promise<IdentityProvider>
  static open(config: JsIdentityManagerConfig): Promise<IdentityProvider>
  acquireLease(request: JsProviderLeaseRequest): Promise<JsProviderLease>
}
export type JsIdentityProvider = IdentityProvider

export declare class ManagedIdentity {
  reference(): Promise<JsIdentityRef>
  publicIdentity(): Promise<any>
  sign(request: JsSignRequest): Promise<JsSignature>
  verify(request: JsVerifyRequest): Promise<string>
  signOriginProof(request: JsOriginProofRequest): Promise<any>
  prepareDocumentChange(request: any): Promise<JsDocumentChangeSession>
  resumeDocumentChange(): Promise<JsDocumentChangeSession | null>
}
export type JsManagedIdentity = ManagedIdentity

export declare class PreparedIdentityMaterialImport {
  offer(): any
  complete(token: string, envelopes: any): Promise<any>
}
export type JsPreparedIdentityMaterialImport = PreparedIdentityMaterialImport

export declare class PreparedProviderAdoption {
  offer(): any
  complete(token: string, envelope: any): Promise<any>
}
export type JsPreparedProviderAdoption = PreparedProviderAdoption

export declare class PreparedRootImport {
  offer(): any
  complete(token: string, envelope: any): Promise<string>
}
export type JsPreparedRootImport = PreparedRootImport

export declare class ProviderLease {
  dispose(): void
  list(): Promise<any>
  publicIdentity(identity: JsIdentityRef): Promise<any>
  create(request: any): Promise<any>
  sign(identity: JsIdentityRef, request: JsSignRequest): Promise<JsSignature>
  signOriginProof(identity: JsIdentityRef, request: JsOriginProofRequest): Promise<any>
  prepareHttpSignature(request: JsExactHttpSigningRequest): Promise<any>
  ecdhSealed(request: JsSealedKeyAgreementRequest): Promise<any>
  exportRootKeySealed(request: JsSealedRootExportRequest): Promise<any>
  prepareLegacyRootImport(request: JsSealedRootImportPreparation): Promise<JsPreparedRootImport>
  prepareIdentityMaterialImport(request: JsSealedIdentityImportPreparation): Promise<JsPreparedIdentityMaterialImport>
  prepareProviderAdoption(request: JsSealedProviderAdoptionPreparation): Promise<JsPreparedProviderAdoption>
}
export type JsProviderLease = ProviderLease

export interface JsExactHttpSigningRequest {
  identity: JsIdentityRef
  kid?: string
  url: string
  method: string
  headers: Array<JsHttpHeader>
  body?: Buffer
  nonce?: string
  created?: number
  expires?: number
  coveredComponents?: Array<string>
}

export interface JsHttpHeader {
  name: string
  value: string
}

export interface JsIdentityManagerConfig {
  stateRoot: string
  rootKeyKind: string
  keyId?: string
  environmentVariable?: string
  rootKey?: Buffer
  service?: string
  account?: string
  fallbackToLocalFile?: boolean
}

export interface JsIdentityRef {
  storeId: string
  identityId: string
  did: string
}

export interface JsOriginProofOptions {
  created?: number
  expires?: number
  nonce?: string
}

export interface JsOriginProofRequest {
  method: string
  meta: any
  body: any
  kid?: string
  options?: JsOriginProofOptions
}

export interface JsProviderLeaseRequest {
  consumer: string
  capabilities: Array<string>
  ttlSeconds: number
}

export interface JsSealedIdentityImportPreparation {
  remote: any
  didWba: boolean
  keys: any
  requestId: string
}

export interface JsSealedKeyAgreementRequest {
  identity: JsIdentityRef
  kid: string
  peerPublic: Buffer
  recipientPublicKey: Buffer
  requestId: string
}

export interface JsSealedProviderAdoptionPreparation {
  stateRoot: string
  target: any
  requestId: string
}

export interface JsSealedRootExportRequest {
  identity: JsIdentityRef
  kid: string
  recipientPublicKey: Buffer
  requestId: string
  userPresenceConfirmed: boolean
}

export interface JsSealedRootImportPreparation {
  identity: JsIdentityRef
  evidence: any
  encoding: string
  requestId: string
}

export interface JsSignature {
  kid: string
  algorithm: string
  bytes: Buffer
}

export interface JsSignRequest {
  purpose: string
  domain?: string
  kid?: string
  payload: Buffer
}

export interface JsVerifyRequest {
  purpose: string
  domain?: string
  kid: string
  payload: Buffer
  signature: Buffer
}
