/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class DocumentChangeSession {
  candidate(): Promise<any>
  beginPublication(): Promise<any>
  complete(attempt: any, result: any): Promise<any>
  reconcile(observation: any): Promise<any>
}
export type JsDocumentChangeSession = DocumentChangeSession

export declare class IdentityManager {
  static initialize(config: JsIdentityManagerConfig): Promise<IdentityManager>
  static open(config: JsIdentityManagerConfig): Promise<IdentityManager>
  info(): Promise<any>
  list(): Promise<any>
  create(request: any): Promise<JsManagedIdentity>
  get(identity: JsIdentityRef): Promise<JsManagedIdentity>
  delete(identity: JsIdentityRef): Promise<void>
  recover(): Promise<any>
}
export type JsIdentityManager = IdentityManager

export declare class ManagedIdentity {
  reference(): Promise<JsIdentityRef>
  publicIdentity(): Promise<any>
  sign(request: JsSignRequest): Promise<JsSignature>
  verify(request: JsVerifyRequest): Promise<string>
  signOriginProof(request: JsOriginProofRequest): Promise<any>
  prepareDocumentChange(request: any): Promise<JsDocumentChangeSession>
  resumeDocumentChange(): Promise<JsDocumentChangeSession | null>
}
export type JsManagedIdentity = ManagedIdentity

export interface JsIdentityManagerConfig {
  stateRoot: string
  rootKeyKind: string
  keyId?: string
  environmentVariable?: string
  rootKey?: Buffer
  service?: string
  account?: string
  fallbackToLocalFile?: boolean
}

export interface JsIdentityRef {
  storeId: string
  identityId: string
  did: string
}

export interface JsOriginProofOptions {
  created?: number
  expires?: number
  nonce?: string
}

export interface JsOriginProofRequest {
  method: string
  meta: any
  body: any
  kid?: string
  options?: JsOriginProofOptions
}

export interface JsSignature {
  kid: string
  algorithm: string
  bytes: Buffer
}

export interface JsSignRequest {
  purpose: string
  domain?: string
  kid?: string
  payload: Buffer
}

export interface JsVerifyRequest {
  purpose: string
  domain?: string
  kid: string
  payload: Buffer
  signature: Buffer
}
