import { copyFileSync, existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('..', import.meta.url))
const publicJs = join(root, 'index.js')
const publicDts = join(root, 'index.d.ts')
const nativeJs = join(root, 'native.cjs')
const nativeDts = join(root, 'native.d.ts')
const jsTemplate = join(root, 'scripts', 'index.js.template')
const dtsTemplate = join(root, 'scripts', 'index.d.ts.template')
const currentJs = readFileSync(publicJs, 'utf8')
const currentDts = readFileSync(publicDts, 'utf8')
const expectedJs = readFileSync(jsTemplate, 'utf8')
const expectedDts = readFileSync(dtsTemplate, 'utf8')

if (currentJs === expectedJs && currentDts === expectedDts) {
  if (!existsSync(nativeJs) || !existsSync(nativeDts)) {
    throw new Error('wrapped outputs exist without their generated native files')
  }
} else {
  if (
    !currentJs.includes('auto-generated by NAPI-RS') ||
    !currentDts.includes('auto-generated by NAPI-RS')
  ) {
    throw new Error('refusing to wrap files that are neither generated nor already wrapped')
  }
  copyFileSync(publicJs, nativeJs)
  copyFileSync(publicDts, nativeDts)
  copyFileSync(jsTemplate, publicJs)
  copyFileSync(dtsTemplate, publicDts)
}
